"""empty message

Revision ID: 1cdaa4c51459
Revises: dbf03ac3f199
Create Date: 2021-08-29 16:08:23.849629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdaa4c51459'
down_revision = 'dbf03ac3f199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_answer_to_questions', 'have_as_answer', type_='foreignkey')
    op.drop_constraint('fk_possible_answers', 'have_as_answer', type_='foreignkey')
    op.create_foreign_key('fk_possible_answers', 'have_as_answer', 'possible_answers', ['possible_answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_answer_to_questions', 'have_as_answer', 'answers_to_questions', ['answer_to_questions_id', 'question_id'], ['id', 'question_id'], ondelete='CASCADE')
    op.drop_constraint('questions_activated_by_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'questions', ['activated_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_activated_by_fkey', 'questions', 'questions', ['activated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_answer_to_questions', 'have_as_answer', type_='foreignkey')
    op.drop_constraint('fk_possible_answers', 'have_as_answer', type_='foreignkey')
    op.create_foreign_key('fk_possible_answers', 'have_as_answer', 'possible_answers', ['possible_answer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_answer_to_questions', 'have_as_answer', 'answers_to_questions', ['answer_to_questions_id', 'question_id'], ['id', 'question_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
