"""empty message

Revision ID: 2893eed52d0f
Revises: 7409eac83319
Create Date: 2021-08-18 15:27:41.657808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2893eed52d0f'
down_revision = '7409eac83319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers_to_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['quiz_answers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id', 'question_id')
    )
    op.alter_column('questions', 'activant',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('questions', 'activant',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('answers_to_questions')
    # ### end Alembic commands ###
