"""empty message

Revision ID: 429c964e03b9
Revises: 492dcb98a7ba
Create Date: 2021-08-19 23:39:56.761292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429c964e03b9'
down_revision = '492dcb98a7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'activant_answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('activant_answer_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'questions', 'possible_answers', ['activant_answer_id'], ['id'])
    # ### end Alembic commands ###
