"""empty message

Revision ID: 660c45faa647
Revises: 556f7021bb72
Create Date: 2021-08-13 16:29:47.118659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660c45faa647'
down_revision = '556f7021bb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('activable_question', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('type_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('activant_answer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'questions', ['activable_question'], ['id'])
    op.create_foreign_key(None, 'questions', 'possible_answers', ['activant_answer_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'questions_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'questions_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'activant_answer_id')
    op.drop_column('questions', 'type_id')
    op.drop_column('questions', 'category_id')
    op.drop_column('questions', 'activable_question')
    # ### end Alembic commands ###
