"""empty message

Revision ID: 9ef547a5b087
Revises: 8dc121ce29dc
Create Date: 2021-08-04 16:57:10.339366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef547a5b087'
down_revision = '8dc121ce29dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers_to_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('possible_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('answers')
    op.add_column('questions', sa.Column('choice_question', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('activant', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('activable_question', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'questions_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'questions', ['activable_question'], ['id'])
    op.create_foreign_key(None, 'questions', 'questions_category', ['category_id'], ['id'])
    op.drop_column('questions', 'activable')
    op.add_column('quizzes', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('quizzes_owner_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['author_id'], ['id'])
    op.drop_column('quizzes', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_owner_id_fkey', 'quizzes', 'users', ['owner_id'], ['id'])
    op.drop_column('quizzes', 'author_id')
    op.add_column('questions', sa.Column('activable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'type_id')
    op.drop_column('questions', 'category_id')
    op.drop_column('questions', 'activable_question')
    op.drop_column('questions', 'activant')
    op.drop_column('questions', 'choice_question')
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='answers_quiz_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='answers_pkey')
    )
    op.drop_table('possible_answers')
    op.drop_table('answers_to_questions')
    op.drop_table('questions_type')
    op.drop_table('questions_category')
    # ### end Alembic commands ###
