"""empty message

Revision ID: a37341868c77
Revises: 2893eed52d0f
Create Date: 2021-08-18 15:43:07.898938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37341868c77'
down_revision = '2893eed52d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('have_as_answer',
    sa.Column('possible_answers_id', sa.Integer(), nullable=False),
    sa.Column('answers_to_questions_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['possible_answers_id'], ['possible_answers.id'], ),
    sa.PrimaryKeyConstraint('possible_answers_id', 'answers_to_questions_id', 'question_id')
    )
    op.create_table('answers_to_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['quiz_answers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers_to_questions')
    op.drop_table('have_as_answer')
    # ### end Alembic commands ###
