"""empty message

Revision ID: c2711190d39d
Revises: 2fe85c423666
Create Date: 2021-08-28 16:55:50.456917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2711190d39d'
down_revision = '2fe85c423666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_activated', sa.Boolean(), nullable=True))
    op.add_column('questions', sa.Column('activated_by', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('activated_by_answer_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_activable_question_fkey', 'questions', type_='foreignkey')
    op.drop_constraint('questions_activant_answer_id_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'questions', ['activated_by'], ['id'])
    op.create_foreign_key(None, 'questions', 'possible_answers', ['activated_by_answer_id'], ['id'])
    op.drop_column('questions', 'activant')
    op.drop_column('questions', 'activable_question')
    op.drop_column('questions', 'activant_answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('activant_answer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('activable_question', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('activant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_activant_answer_id_fkey', 'questions', 'possible_answers', ['activant_answer_id'], ['id'])
    op.create_foreign_key('questions_activable_question_fkey', 'questions', 'questions', ['activable_question'], ['id'])
    op.drop_column('questions', 'activated_by_answer_id')
    op.drop_column('questions', 'activated_by')
    op.drop_column('questions', 'is_activated')
    # ### end Alembic commands ###
