"""empty message

Revision ID: ce0165d64d91
Revises: 178c3e56b677
Create Date: 2021-08-29 13:46:15.050817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0165d64d91'
down_revision = '178c3e56b677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_answer_to_questions', 'have_as_answer', type_='foreignkey')
    op.drop_constraint('fk_possible_answers', 'have_as_answer', type_='foreignkey')
    op.create_foreign_key('fk_possible_answers', 'have_as_answer', 'possible_answers', ['possible_answer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_answer_to_questions', 'have_as_answer', 'answers_to_questions', ['answer_to_questions_id', 'question_id'], ['id', 'question_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_answer_to_questions', 'have_as_answer', type_='foreignkey')
    op.drop_constraint('fk_possible_answers', 'have_as_answer', type_='foreignkey')
    op.create_foreign_key('fk_possible_answers', 'have_as_answer', 'possible_answers', ['possible_answer_id'], ['id'])
    op.create_foreign_key('fk_answer_to_questions', 'have_as_answer', 'answers_to_questions', ['answer_to_questions_id', 'question_id'], ['id', 'question_id'])
    # ### end Alembic commands ###
