"""empty message

Revision ID: dd46aa0fa07b
Revises: eb608ea74dde
Create Date: 2021-08-16 13:17:35.152727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd46aa0fa07b'
down_revision = 'eb608ea74dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers_to_questions', type_='foreignkey')
    op.drop_column('answers_to_questions', 'quiz_id')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('answers_to_questions', sa.Column('quiz_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'answers_to_questions', 'quizzes', ['quiz_id'], ['id'])
    # ### end Alembic commands ###
