"""empty message

Revision ID: f519a99802af
Revises: a37341868c77
Create Date: 2021-08-18 17:28:48.916316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f519a99802af'
down_revision = 'a37341868c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('have_as_answer',
    sa.Column('possible_answer_id', sa.Integer(), nullable=False),
    sa.Column('answer_to_questions', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_to_questions'], ['answers_to_questions.id'], ),
    sa.ForeignKeyConstraint(['possible_answer_id'], ['possible_answers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['answers_to_questions.question_id'], ),
    sa.PrimaryKeyConstraint('possible_answer_id', 'answer_to_questions', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('have_as_answer')
    # ### end Alembic commands ###
