"""empty message

Revision ID: fcee0c8b9a7c
Revises: 137a50940062
Create Date: 2021-08-17 11:23:21.399584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcee0c8b9a7c'
down_revision = '137a50940062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers_to_questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'answers_to_questions', 'quiz_answers', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers_to_questions', type_='foreignkey')
    op.alter_column('answers_to_questions', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
